### ISSUE TITLE
Provide Variable for slack alerting

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf-package-big-bang#23]
As a consumer of the distros, I would like to be able to provide a deploy time variable that configures all alerts to be sent to a slack channel:

- [ ] Alertmanager
- [ ] Grafana
- [ ] Flux Notification Controller

**Comment by runyontr** [comment]
By default, turn off all the alertmanager alerts except:

* PVC Storage getting filled up
* Unhealthy pods
* failed HRs

**Comment by runyontr** [comment]
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: provider-sample
  namespace: flux-system
spec:
  address: ###ZARF_VAR_SLACK_URL###
  channel: ###ZARF_VAR_SLACK_CHANNEL###
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: alert-sample
  namespace: flux-system
spec:
  summary: "Big Bang Deployment"
```
