### ISSUE TITLE
Define how this repo & package should be leveraged

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/zarf-package-big-bang#25]
* fork this repo or a reference to the repo?
* define preferred way to customize one's BB deployment (custom-values.yaml at the end of the values list)?
* kustomize?

**Comment by runyontr** [comment]
Yes, we should clearly define this.  What the plan is:


1. This repo will publish a Zarf package for the BigBang distro into a OCI registry ( blocked by https://github.com/defenseunicorns/zarf/pull/1402 ) to `ghcr.io/defenseunicorns/big-bang-distro:1.54.0` (or something?)
2. End users will either do a straight `zarf package deploy oci://ghcr.io/defenseunicorns/big-bang-distro:1.54.0`
3. Zarf package devs could import that as a component:

```yaml
kind: ZarfPackageConfig
metadata:
  name: "Customer Environment"
  description: "Example of the UDS"

components:
...
- name: bigbang
  required: true
  import:
    oci:  ghcr.io/defenseunicorns/big-bang-distro:1.54.0
...
```
